import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { collectDist, emitModule } from "../embed-web.js";

/**
 * Embed-generator unit tests. The fake dist mimics a Vite build output:
 * a shell, hashed assets, and a nested directory holding a binary asset with
 * deliberately invalid UTF-8 — the base64 round-trip must be byte-exact.
 */
let root = "";

// Invalid-UTF-8 on purpose: 0x89 0x50 lead a PNG, 0xff/0xfe are never valid
// UTF-8 bytes, 0xc3 0x28 is a truncated 2-byte sequence.
const PNG_BYTES = new Uint8Array([0x89, 0x50, 0xff, 0xfe, 0xc3, 0x28, 0x00, 0x42]);

beforeAll(async () => {
  root = await mkdtemp(join(tmpdir(), "subshell-embed-test-"));
  await mkdir(join(root, "assets"), { recursive: true });
  await mkdir(join(root, "icons", "deep"), { recursive: true });
  await writeFile(join(root, "index.html"), "<!doctype html><html><title>subshell</title></html>");
  await writeFile(join(root, "assets", "app.js"), 'console.log("hi");');
  await writeFile(join(root, "icons", "deep", "icon.png"), PNG_BYTES);
});

afterAll(async () => {
  await rm(root, { recursive: true, force: true });
});

describe("collectDist", () => {
  test("maps every dist file to base64 under a POSIX dist-relative path (recursive)", async () => {
    const map = await collectDist(root);
    expect(Object.keys(map).sort()).toEqual(["assets/app.js", "icons/deep/icon.png", "index.html"]);
    expect(Buffer.from(map["index.html"], "base64").toString("utf8")).toContain("<title>subshell</title>");
    expect(Buffer.from(map["assets/app.js"], "base64").toString("utf8")).toBe('console.log("hi");');
  });

  test("binary assets round-trip byte-identically through base64", async () => {
    const map = await collectDist(root);
    const original = await readFile(join(root, "icons", "deep", "icon.png"));
    const decoded = Buffer.from(map["icons/deep/icon.png"], "base64");
    expect(Buffer.compare(decoded, original)).toBe(0);
    expect([...decoded]).toEqual([...PNG_BYTES]);
  });

  test("a dist without index.html throws (the shell is mandatory)", async () => {
    const orphan = await mkdtemp(join(tmpdir(), "subshell-embed-noindex-"));
    try {
      await writeFile(join(orphan, "orphan.js"), "// no shell here");
      await expect(collectDist(orphan)).rejects.toThrow(/index\.html/);
    } finally {
      await rm(orphan, { recursive: true, force: true });
    }
  });

  test("a missing dist directory rejects (never an empty silent map)", async () => {
    const nowhere = join(root, "..", "subshell-embed-does-not-exist");
    await expect(collectDist(nowhere)).rejects.toThrow();
  });
});

describe("emitModule", () => {
  test("emits the generated header, EMBEDDED=true and the EMBEDDED_WEB map", () => {
    const source = emitModule({ "index.html": "aHRtbA==", "assets/app.js": "Kg==" });
    expect(source).toContain("GENERATED by scripts/embed-web.ts — do not edit");
    expect(source).toContain("export const EMBEDDED = true;");
    expect(source).toContain("export const EMBEDDED_WEB: Record<string, string> = {");
    expect(source).toContain('"index.html": "aHRtbA=="');
    expect(source).toContain('"assets/app.js": "Kg==",');
  });

  test("keys are sorted, so regenerating the same dist is byte-identical", () => {
    const a = emitModule({ "z.js": "", "index.html": "x", "assets/app.js": "y" });
    const b = emitModule({ "index.html": "x", "assets/app.js": "y", "z.js": "" });
    expect(a).toBe(b);
    expect(a.indexOf('"assets/app.js"')).toBeLessThan(a.indexOf('"index.html"'));
    expect(a.indexOf('"index.html"')).toBeLessThan(a.indexOf('"z.js"'));
  });

  test("an empty map still emits a compilable module", () => {
    const source = emitModule({});
    expect(source).toContain("export const EMBEDDED = true;");
    expect(source).toContain("export const EMBEDDED_WEB: Record<string, string> = {");
    expect(source).toContain("};");
  });
});
