#!/usr/bin/env bun
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { parseManifest } from "@subshell-ai/plugin-api";
import type { EmbeddedFile } from "../builtin-source.js";

/**
 * Bakes the built-in plugins into `generated/embedded-plugins.ts`.
 *
 * Installing a built-in has to work with no network, so the binary carries the
 * bytes. Reading `packages/plugins/*` at runtime would not do: `bun build
 * --compile` bundles what it can SEE, and the compiled agent has no repo
 * beside it. Same reasoning, and the same tracked-stub shape, as
 * `apps/server/api/src/scripts/embed-web.ts`.
 *
 * Runs during `build`, after the plugin packages build, which turbo already
 * orders through `dependsOn: ["^build"]`.
 */

const PACKAGE_ROOT = resolve(import.meta.dir, "..", "..");
const PLUGINS_ROOT = resolve(PACKAGE_ROOT, "..", "plugins");
const OUT = join(PACKAGE_ROOT, "src", "generated", "embedded-plugins.ts");

/** Every file under `dir`, as paths relative to it. */
async function filesUnder(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true, recursive: true })) {
    if (!entry.isFile()) continue;
    out.push(relative(dir, join(entry.parentPath, entry.name)));
  }
  return out;
}

async function main(): Promise<void> {
  const ids = (await readdir(PLUGINS_ROOT, { withFileTypes: true }))
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  const embedded: Record<string, { manifest: unknown; files: Record<string, EmbeddedFile> }> = {};

  for (const id of ids) {
    const dir = join(PLUGINS_ROOT, id);
    const pkgRaw = await readFile(join(dir, "package.json"), "utf8");
    const manifest = parseManifest(JSON.parse(pkgRaw) as unknown);
    if ("error" in manifest) {
      // Refuse rather than embed something the loader will reject later: a
      // built-in with a broken manifest is a build-time mistake, and this is
      // the build.
      throw new Error(`embed-plugins: ${id} has an invalid manifest: ${manifest.error}`);
    }

    const files: Record<string, EmbeddedFile> = { "package.json": pkgRaw };
    const distDir = join(dir, dirname(manifest.entry));
    let distFiles: string[];
    try {
      distFiles = await filesUnder(distDir);
    } catch {
      throw new Error(`embed-plugins: ${id} has no built output at ${distDir}; run \`turbo build\` first`);
    }
    for (const rel of distFiles) {
      // Only what an install must write. `.d.ts` is for a plugin's authors,
      // not for the machine that runs it.
      if (rel.endsWith(".d.ts") || rel.endsWith(".map")) continue;
      files[join(dirname(manifest.entry), rel)] = await readFile(join(distDir, rel), "utf8");
    }
    if (!(manifest.entry in files)) {
      throw new Error(`embed-plugins: ${id}'s entry ${manifest.entry} is not in its built output`);
    }

    // The icon lives at the package root rather than under the entry's dist
    // directory, so it is read by name. Base64 because it may be a PNG and
    // this record is about to be JSON.stringify'd.
    //
    // Refused rather than skipped: a BUILT-IN that declares an icon it does
    // not ship is a mistake in this repo, and this is the build. (The runtime
    // reader tolerates it — see `builtin-source.ts`.)
    if (manifest.icon !== undefined) {
      let iconBytes: Buffer;
      try {
        iconBytes = await readFile(join(dir, manifest.icon));
      } catch {
        throw new Error(`embed-plugins: ${id} declares icon ${manifest.icon}, which is not in the package`);
      }
      files[manifest.icon] = { b64: iconBytes.toString("base64") };
    }
    embedded[manifest.id] = { manifest, files };
  }

  const header = `import type { EmbeddedPlugin } from "../builtin-source.js";

/**
 * The built-in plugins, as bytes.
 *
 * **GENERATED by \`src/scripts/embed-plugins.ts\`. Do not edit, and do not
 * commit this form:** the tracked copy is an empty stub, restored with
 * \`git checkout\` the way \`embedded-web.ts\` is.
 */
export const EMBEDDED_PLUGINS: Record<string, EmbeddedPlugin> = `;

  await writeFile(OUT, `${header}${JSON.stringify(embedded, null, 2)};\n`, "utf8");
  const total = Object.values(embedded).reduce((n, p) => n + Object.keys(p.files).length, 0);
  console.log(
    `embed-plugins: ${Object.keys(embedded).length} plugins, ${total} files -> ${relative(PACKAGE_ROOT, OUT)}`,
  );
}

await main();
