import { afterEach, describe, expect, it } from "bun:test";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseManifest } from "@subshell-ai/plugin-api";
import { builtInIds, readBuiltIn } from "../builtin-source.js";
import { EMBEDDED_PLUGINS } from "../generated/embedded-plugins.js";

/**
 * Installing a built-in must work with no network, so a build carries each
 * plugin's bytes: from the checkout when there is one, from the generated
 * module when there is not.
 *
 * Every case iterates {@link BUILT_INS} rather than whatever the source
 * happens to return, so a resolver that answered nothing would fail all of
 * them instead of passing vacuously.
 */
const BUILT_INS = ["claude-code", "codex", "hermes", "opencode", "pi", "terminal"] as const;

describe("built-in plugin bytes", () => {
  it("offers exactly the six built-ins", async () => {
    expect(await builtInIds()).toEqual([...BUILT_INS]);
  });

  it("answers null for an unknown id rather than throwing", async () => {
    expect(await readBuiltIn("not-a-plugin")).toBeNull();
  });

  it("the tracked generated module is an empty stub", () => {
    // 84 KB of generated bytes committed by accident would churn on every
    // plugin change. The release pipelines fill it; the repo does not carry it.
    expect(EMBEDDED_PLUGINS).toEqual({});
  });

  for (const id of BUILT_INS) {
    it(`${id}: carries a package.json and its entry file`, async () => {
      const plugin = await readBuiltIn(id);
      expect(plugin).not.toBeNull();
      if (!plugin) return;
      expect("package.json" in plugin.files).toBe(true);
      expect(plugin.manifest.entry in plugin.files).toBe(true);
    });

    it(`${id}: the package.json parses as the manifest beside it`, async () => {
      // The two must agree, or an install writes files describing a different
      // plugin from the one the caller believes it wrote.
      const plugin = await readBuiltIn(id);
      if (!plugin) throw new Error(`no bytes for ${id}`);
      const parsed = parseManifest(JSON.parse(plugin.files["package.json"] as string));
      expect("error" in parsed).toBe(false);
      if ("error" in parsed) return;
      expect(parsed).toEqual(plugin.manifest);
    });

    it(`${id}: the entry is a real module, not an empty placeholder`, async () => {
      const plugin = await readBuiltIn(id);
      if (!plugin) throw new Error(`no bytes for ${id}`);
      expect((plugin.files[plugin.manifest.entry] ?? "").length).toBeGreaterThan(100);
    });

    it(`${id}: the entry imports nothing but node builtins`, async () => {
      // A plugin loaded from disk cannot resolve a bare specifier, so bytes
      // carrying one would install cleanly and then fail at load.
      const plugin = await readBuiltIn(id);
      if (!plugin) throw new Error(`no bytes for ${id}`);
      const rawEntry = plugin.files[plugin.manifest.entry] ?? "";
      // The entry is JavaScript, so it is always text; `files` is typed for
      // bytes because an icon may be a PNG.
      const entry = typeof rawEntry === "string" ? rawEntry : new TextDecoder().decode(rawEntry);
      const bare = [...entry.matchAll(/^import[^"']*["']([^"']+)["']/gm)]
        .map((m) => m[1])
        .filter((spec) => spec !== undefined && !spec.startsWith("node:") && !spec.startsWith("."));
      expect(bare).toEqual([]);
    });

    it(`${id}: carries no .d.ts or sourcemap, which an install must not write`, async () => {
      const plugin = await readBuiltIn(id);
      if (!plugin) throw new Error(`no bytes for ${id}`);
      expect(Object.keys(plugin.files).filter((f) => f.endsWith(".d.ts") || f.endsWith(".map"))).toEqual([]);
    });
  }
});

describe("a built-in this checkout cannot read", () => {
  const BAD_ID = "zz-malformed-fixture";
  const BAD = join(import.meta.dir, "..", "..", "..", "plugins", BAD_ID);

  afterEach(() => {
    rmSync(BAD, { recursive: true, force: true });
  });

  it("answers null instead of throwing out of its caller", async () => {
    // `readBuiltIn` is called in a LOOP over every installed plugin, so a
    // throw here ended the whole refresh pass and every id sorting after the
    // bad one kept a stale copy with nothing said. `parseManifest` returns
    // its refusal; `JSON.parse` throws, and that half was uncovered.
    mkdirSync(BAD, { recursive: true });
    writeFileSync(join(BAD, "package.json"), "{ not json");

    expect(await readBuiltIn(BAD_ID)).toBeNull();
  });
});
