import { readdir, readFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { parseManifest, type SubshellManifest } from "@subshell-ai/plugin-api";
import { EMBEDDED_PLUGINS } from "./generated/embedded-plugins.js";

/**
 * Where a built-in plugin's bytes come from.
 *
 * Two sources, checked in the order `selectStaticPlugin` checks them for the
 * SPA, and for the same reason: **on-disk wins, embedded is the fallback**, so
 * a dev run and a compiled binary behave identically without the repo needing
 * to carry generated bytes.
 *
 * - **From source** (`bun run dev`, every test, a checkout-based service),
 *   `packages/plugins/<id>` is right there, so it is read directly. Nothing is
 *   generated, nothing is committed, and editing a plugin takes effect on the
 *   next read.
 * - **Compiled**, that path does not exist, so the copies baked in by
 *   `scripts/embed-plugins.ts` answer instead. That generation happens in the
 *   release pipelines only, which is what keeps the tracked
 *   `generated/embedded-plugins.ts` an empty stub rather than 84 KB of churn
 *   on every build.
 *
 * The measured caveat that applies to `embedded-web.ts` applies here too: a
 * compiled binary bakes its BUILD-TIME source path into `import.meta.url`, so
 * on the build machine the repo's own `packages/plugins` shadows the embedded
 * copy. Hide that path before asserting embedded mode is live.
 */

/** One plugin's manifest plus every file an install must write. */
export interface EmbeddedPlugin {
  /** The parsed `subshell` block, so a caller need not re-read package.json */
  manifest: SubshellManifest;
  /** Relative path to file content, including `package.json` and the entry */
  files: Record<string, string>;
}

/** Where `packages/plugins` sits relative to this module, when running from source. */
const PLUGINS_ROOT = resolve(import.meta.dir, "..", "..", "plugins");

/** Files an install must never write: they serve a plugin's authors, not the machine running it. */
function isRuntimeFile(rel: string): boolean {
  return !rel.endsWith(".d.ts") && !rel.endsWith(".map");
}

/** Reads one built-in from the checkout, or null when there is no checkout. */
async function fromDisk(id: string): Promise<EmbeddedPlugin | null> {
  const dir = join(PLUGINS_ROOT, id);
  let pkgRaw: string;
  try {
    pkgRaw = await readFile(join(dir, "package.json"), "utf8");
  } catch {
    return null;
  }
  // Inside the guard, not beside it. `parseManifest` returns its refusal, but
  // `JSON.parse` THROWS, and this function is called in a loop over every
  // installed plugin: one malformed package.json in the checkout ended the
  // whole pass, so every id sorting after it silently kept a stale copy. A
  // source we cannot read is a source we cannot install from, which is
  // already what `null` means here.
  let manifest: ReturnType<typeof parseManifest>;
  try {
    manifest = parseManifest(JSON.parse(pkgRaw) as unknown);
  } catch {
    return null;
  }
  if ("error" in manifest) return null;

  const files: Record<string, string> = { "package.json": pkgRaw };
  const distDir = join(dir, dirname(manifest.entry));
  try {
    for (const entry of await readdir(distDir, { withFileTypes: true, recursive: true })) {
      if (!entry.isFile()) continue;
      const rel = relative(distDir, join(entry.parentPath, entry.name));
      if (!isRuntimeFile(rel)) continue;
      files[join(dirname(manifest.entry), rel)] = await readFile(join(distDir, rel), "utf8");
    }
  } catch {
    // Built output missing: the plugin exists in the checkout but has not been
    // built. Not a source we can install from.
    return null;
  }
  if (!(manifest.entry in files)) return null;
  return { manifest, files };
}

/**
 * The bytes for one built-in, or null when this build does not carry it.
 * @param id - plugin id, e.g. "claude-code"
 */
export async function readBuiltIn(id: string): Promise<EmbeddedPlugin | null> {
  return (await fromDisk(id)) ?? EMBEDDED_PLUGINS[id] ?? null;
}

/** Every built-in id this build can install, from whichever source answered. */
export async function builtInIds(): Promise<string[]> {
  const ids = new Set(Object.keys(EMBEDDED_PLUGINS));
  try {
    for (const entry of await readdir(PLUGINS_ROOT, { withFileTypes: true })) {
      if (entry.isDirectory()) ids.add(entry.name);
    }
  } catch {
    // Compiled: no checkout. The embedded set is the whole answer.
  }
  return [...ids].sort();
}
