/**
 * `scripts/embed-web.ts` — the build-time SPA embedder for the compiled
 * `subshell-server` binary (spec 2026-09-03 §4). Walks `apps/server/web/dist`,
 * base64s every file, and OVERWRITES `src/generated/embedded-web.ts` with a
 * static module the memory-mode static plugin imports (project rule: no
 * dynamic imports, so the bytes ship as a plain TS module).
 *
 * Deliberately OUTSIDE the runtime import graph (the agent's `release.ts`
 * precedent): the compiled binary never sees this file, tests import only the
 * pure exports, and the CLI entry is guarded by `import.meta.main`.
 *
 * Release flow (Plan 2 Task E): run this BEFORE `bun build --compile`, then
 * `git checkout -- apps/server/api/src/generated/embedded-web.ts` after publishing
 * so the tracked stub stays the committed state.
 */

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
/** `apps/server/api` — the app whose `src/generated/` this script writes into. */
const SERVER_DIR = resolve(SCRIPT_DIR, "..", "..");

/** Recursively collect every file under `dir` into `out`, keyed dist-relative. */
async function walk(dir: string, base: string, out: Record<string, string>): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });
  // Sorted traversal keeps the emitted map deterministic for identical dists.
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full, base, out);
      continue;
    }
    if (!entry.isFile()) continue;
    // POSIX keys regardless of host separator — the plugin looks up these
    // exact strings, and the dist layout is POSIX everywhere it is built.
    const rel = relative(base, full).split(sep).join("/");
    out[rel] = (await readFile(full)).toString("base64");
  }
}

/**
 * Reads a built frontend dist into a map of POSIX dist-relative path → base64
 * of the exact file bytes (binary assets included — base64 is byte-exact,
 * invalid UTF-8 survives).
 * @param distDir - directory to walk (`apps/server/web/dist` at release time)
 * @throws when `distDir` cannot be read or holds no `index.html` — the SPA
 * shell is mandatory, so a dist without it fails the build loudly here rather
 * than shipping a binary that 500s on every page load.
 */
export async function collectDist(distDir: string): Promise<Record<string, string>> {
  const base = resolve(distDir);
  const map: Record<string, string> = {};
  await walk(base, base, map);
  if (map["index.html"] === undefined) {
    throw new Error(`embed-web: index.html not found in ${base} — run the frontend build first`);
  }
  return map;
}

/**
 * Renders the TypeScript source of the generated module for a collected map.
 * Keys are sorted so regenerating from an identical dist is byte-identical.
 * @param map - the {@link collectDist} output
 */
export function emitModule(map: Record<string, string>): string {
  const keys = Object.keys(map).sort();
  const entries = keys.map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(map[key])},`);
  return [
    "// GENERATED by scripts/embed-web.ts — do not edit",
    `// ${keys.length} file(s) of the built frontend, base64-encoded at release time.`,
    "// Served by embeddedStaticPlugin() when no dist dir is on disk (spec 2026-09-03 §4);",
    "// the tracked stub of this file says EMBEDDED = false and maps nothing.",
    "",
    "export const EMBEDDED = true;",
    "",
    "export const EMBEDDED_WEB: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

/** CLI: `apps/server/web/dist` (relative to `apps/server/api`) → src/generated/embedded-web.ts. */
async function main(): Promise<void> {
  const distDir = resolve(SERVER_DIR, "..", "web", "dist");
  const map = await collectDist(distDir);
  const outPath = join(SERVER_DIR, "src", "generated", "embedded-web.ts");
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, emitModule(map));
  const files = Object.keys(map).length;
  const bytes = Object.values(map).reduce((sum, value) => sum + value.length, 0);
  process.stdout.write(`embed-web: ${files} file(s), ${bytes} base64 bytes from ${distDir} → ${outPath}\n`);
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    process.stderr.write(`embed-web: ${error instanceof Error ? error.message : String(error)}\n`);
    process.exit(1);
  });
}
