import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import path from "node:path";
import robots from "../../app/robots";

/**
 * The discovery layer (robots + sitemap) pinned at the source level.
 *
 * `app/robots.ts` is imported and run directly (it reads only `SITE_ORIGIN`,
 * no macro). `app/sitemap.ts` is NOT imported: like the content-tree test,
 * the suite avoids the macro-compiled page source (a bundler plugin inlines
 * it at build time; bare `bun test` cannot resolve `fumadocs-mdx/macro`).
 * The sitemap is instead checked from its build output, `out/sitemap.xml`,
 * when a build has run — the same skip-until-present stance content-tree
 * uses for `content/docs`. The sitemap's derivation from `source` is exactly
 * what makes it drift-proof, so the generated file, not a hand-list, is the
 * right thing to assert against.
 */

describe("robots", () => {
  test("allows everything and names the sitemap on the real origin", () => {
    const r = robots();
    expect(r.rules).toEqual([{ userAgent: "*", allow: "/" }]);
    expect(r.sitemap).toBe("https://docs.subshell.sh/sitemap.xml");
  });
});

const SITEMAP_OUT = path.join(import.meta.dir, "../../out/sitemap.xml");

if (!fs.existsSync(SITEMAP_OUT)) {
  test("sitemap not built yet — output check skipped", () => {
    console.warn(
      `[seo] SKIP: ${path.relative(process.cwd(), SITEMAP_OUT)} does not exist. ` +
        "The sitemap is generated by the build; this check validates it once `turbo build` has run.",
    );
  });
} else {
  describe("out/sitemap.xml", () => {
    test("every entry is absolute on the real origin; the root is present", () => {
      const xml = fs.readFileSync(SITEMAP_OUT, "utf8");
      const urls = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
      expect(urls.length).toBeGreaterThan(10);
      for (const url of urls) expect(url.startsWith("https://docs.subshell.sh/")).toBe(true);
      expect(urls).toContain("https://docs.subshell.sh/");
    });
  });
}
