/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as NodesIdRouteImport } from './routes/nodes_.$id'
import { Route as PresetsIdRouteImport } from './routes/presets_.$id'
import { Route as SettingsApiKeysRouteImport } from './routes/settings_.api-keys'
import { Route as SettingsAuditRouteImport } from './routes/settings_.audit'
import { Route as SettingsNetworkingRouteImport } from './routes/settings_.networking'
import { Route as SettingsPluginsRouteImport } from './routes/settings_.plugins'
import { Route as SettingsServiceRouteImport } from './routes/settings_.service'
import { Route as SettingsStatusRouteImport } from './routes/settings_.status'
import { Route as SettingsUpdatesRouteImport } from './routes/settings_.updates'
import { Route as SettingsUsersRouteImport } from './routes/settings_.users'
import { Route as SubshellsIdRouteImport } from './routes/subshells_.$id'
import { Route as WorkspacesIdRouteImport } from './routes/workspaces_.$id'
import { Route as NodesIdConfigRouteImport } from './routes/nodes_.$id.config'
import { Route as NodesIdLogsRouteImport } from './routes/nodes_.$id.logs'
import { Route as NodesIdServiceRouteImport } from './routes/nodes_.$id.service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIdRoute = NodesIdRouteImport.update({
  id: '/nodes_/$id',
  path: '/nodes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsIdRoute = PresetsIdRouteImport.update({
  id: '/presets_/$id',
  path: '/presets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings_/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/settings_/audit',
  path: '/settings/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNetworkingRoute = SettingsNetworkingRouteImport.update({
  id: '/settings_/networking',
  path: '/settings/networking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/settings_/plugins',
  path: '/settings/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsServiceRoute = SettingsServiceRouteImport.update({
  id: '/settings_/service',
  path: '/settings/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStatusRoute = SettingsStatusRouteImport.update({
  id: '/settings_/status',
  path: '/settings/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUpdatesRoute = SettingsUpdatesRouteImport.update({
  id: '/settings_/updates',
  path: '/settings/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings_/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SubshellsIdRoute = SubshellsIdRouteImport.update({
  id: '/subshells_/$id',
  path: '/subshells/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIdRoute = WorkspacesIdRouteImport.update({
  id: '/workspaces_/$id',
  path: '/workspaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIdConfigRoute = NodesIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => NodesIdRoute,
} as any)
const NodesIdLogsRoute = NodesIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => NodesIdRoute,
} as any)
const NodesIdServiceRoute = NodesIdServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => NodesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/preferences': typeof PreferencesRoute
  '/presets': typeof PresetsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/workspaces': typeof WorkspacesRoute
  '/nodes/$id': typeof NodesIdRouteWithChildren
  '/presets/$id': typeof PresetsIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/networking': typeof SettingsNetworkingRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/service': typeof SettingsServiceRoute
  '/settings/status': typeof SettingsStatusRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/subshells/$id': typeof SubshellsIdRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/nodes/$id/config': typeof NodesIdConfigRoute
  '/nodes/$id/logs': typeof NodesIdLogsRoute
  '/nodes/$id/service': typeof NodesIdServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/preferences': typeof PreferencesRoute
  '/presets': typeof PresetsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/workspaces': typeof WorkspacesRoute
  '/nodes/$id': typeof NodesIdRouteWithChildren
  '/presets/$id': typeof PresetsIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/networking': typeof SettingsNetworkingRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/service': typeof SettingsServiceRoute
  '/settings/status': typeof SettingsStatusRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/subshells/$id': typeof SubshellsIdRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/nodes/$id/config': typeof NodesIdConfigRoute
  '/nodes/$id/logs': typeof NodesIdLogsRoute
  '/nodes/$id/service': typeof NodesIdServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/preferences': typeof PreferencesRoute
  '/presets': typeof PresetsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/workspaces': typeof WorkspacesRoute
  '/nodes_/$id': typeof NodesIdRouteWithChildren
  '/presets_/$id': typeof PresetsIdRoute
  '/settings_/api-keys': typeof SettingsApiKeysRoute
  '/settings_/audit': typeof SettingsAuditRoute
  '/settings_/networking': typeof SettingsNetworkingRoute
  '/settings_/plugins': typeof SettingsPluginsRoute
  '/settings_/service': typeof SettingsServiceRoute
  '/settings_/status': typeof SettingsStatusRoute
  '/settings_/updates': typeof SettingsUpdatesRoute
  '/settings_/users': typeof SettingsUsersRoute
  '/subshells_/$id': typeof SubshellsIdRoute
  '/workspaces_/$id': typeof WorkspacesIdRoute
  '/nodes_/$id/config': typeof NodesIdConfigRoute
  '/nodes_/$id/logs': typeof NodesIdLogsRoute
  '/nodes_/$id/service': typeof NodesIdServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/new'
    | '/nodes'
    | '/preferences'
    | '/presets'
    | '/settings'
    | '/setup'
    | '/workspaces'
    | '/nodes/$id'
    | '/presets/$id'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/networking'
    | '/settings/plugins'
    | '/settings/service'
    | '/settings/status'
    | '/settings/updates'
    | '/settings/users'
    | '/subshells/$id'
    | '/workspaces/$id'
    | '/nodes/$id/config'
    | '/nodes/$id/logs'
    | '/nodes/$id/service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/new'
    | '/nodes'
    | '/preferences'
    | '/presets'
    | '/settings'
    | '/setup'
    | '/workspaces'
    | '/nodes/$id'
    | '/presets/$id'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/networking'
    | '/settings/plugins'
    | '/settings/service'
    | '/settings/status'
    | '/settings/updates'
    | '/settings/users'
    | '/subshells/$id'
    | '/workspaces/$id'
    | '/nodes/$id/config'
    | '/nodes/$id/logs'
    | '/nodes/$id/service'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/new'
    | '/nodes'
    | '/preferences'
    | '/presets'
    | '/settings'
    | '/setup'
    | '/workspaces'
    | '/nodes_/$id'
    | '/presets_/$id'
    | '/settings_/api-keys'
    | '/settings_/audit'
    | '/settings_/networking'
    | '/settings_/plugins'
    | '/settings_/service'
    | '/settings_/status'
    | '/settings_/updates'
    | '/settings_/users'
    | '/subshells_/$id'
    | '/workspaces_/$id'
    | '/nodes_/$id/config'
    | '/nodes_/$id/logs'
    | '/nodes_/$id/service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  NodesRoute: typeof NodesRoute
  PreferencesRoute: typeof PreferencesRoute
  PresetsRoute: typeof PresetsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  WorkspacesRoute: typeof WorkspacesRoute
  NodesIdRoute: typeof NodesIdRouteWithChildren
  PresetsIdRoute: typeof PresetsIdRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsNetworkingRoute: typeof SettingsNetworkingRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsServiceRoute: typeof SettingsServiceRoute
  SettingsStatusRoute: typeof SettingsStatusRoute
  SettingsUpdatesRoute: typeof SettingsUpdatesRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SubshellsIdRoute: typeof SubshellsIdRoute
  WorkspacesIdRoute: typeof WorkspacesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes_/$id': {
      id: '/nodes_/$id'
      path: '/nodes/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof NodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets_/$id': {
      id: '/presets_/$id'
      path: '/presets/$id'
      fullPath: '/presets/$id'
      preLoaderRoute: typeof PresetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/api-keys': {
      id: '/settings_/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/audit': {
      id: '/settings_/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/networking': {
      id: '/settings_/networking'
      path: '/settings/networking'
      fullPath: '/settings/networking'
      preLoaderRoute: typeof SettingsNetworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/plugins': {
      id: '/settings_/plugins'
      path: '/settings/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/service': {
      id: '/settings_/service'
      path: '/settings/service'
      fullPath: '/settings/service'
      preLoaderRoute: typeof SettingsServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/status': {
      id: '/settings_/status'
      path: '/settings/status'
      fullPath: '/settings/status'
      preLoaderRoute: typeof SettingsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/updates': {
      id: '/settings_/updates'
      path: '/settings/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof SettingsUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/users': {
      id: '/settings_/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subshells_/$id': {
      id: '/subshells_/$id'
      path: '/subshells/$id'
      fullPath: '/subshells/$id'
      preLoaderRoute: typeof SubshellsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$id': {
      id: '/workspaces_/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof WorkspacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes_/$id/config': {
      id: '/nodes_/$id/config'
      path: '/config'
      fullPath: '/nodes/$id/config'
      preLoaderRoute: typeof NodesIdConfigRouteImport
      parentRoute: typeof NodesIdRoute
    }
    '/nodes_/$id/logs': {
      id: '/nodes_/$id/logs'
      path: '/logs'
      fullPath: '/nodes/$id/logs'
      preLoaderRoute: typeof NodesIdLogsRouteImport
      parentRoute: typeof NodesIdRoute
    }
    '/nodes_/$id/service': {
      id: '/nodes_/$id/service'
      path: '/service'
      fullPath: '/nodes/$id/service'
      preLoaderRoute: typeof NodesIdServiceRouteImport
      parentRoute: typeof NodesIdRoute
    }
  }
}

interface NodesIdRouteChildren {
  NodesIdConfigRoute: typeof NodesIdConfigRoute
  NodesIdLogsRoute: typeof NodesIdLogsRoute
  NodesIdServiceRoute: typeof NodesIdServiceRoute
}

const NodesIdRouteChildren: NodesIdRouteChildren = {
  NodesIdConfigRoute: NodesIdConfigRoute,
  NodesIdLogsRoute: NodesIdLogsRoute,
  NodesIdServiceRoute: NodesIdServiceRoute,
}

const NodesIdRouteWithChildren =
  NodesIdRoute._addFileChildren(NodesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  NodesRoute: NodesRoute,
  PreferencesRoute: PreferencesRoute,
  PresetsRoute: PresetsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  WorkspacesRoute: WorkspacesRoute,
  NodesIdRoute: NodesIdRouteWithChildren,
  PresetsIdRoute: PresetsIdRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsNetworkingRoute: SettingsNetworkingRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsServiceRoute: SettingsServiceRoute,
  SettingsStatusRoute: SettingsStatusRoute,
  SettingsUpdatesRoute: SettingsUpdatesRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SubshellsIdRoute: SubshellsIdRoute,
  WorkspacesIdRoute: WorkspacesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
