/**
 * `src/scripts/embed-web.ts` — the build-time SPA embedder for the compiled
 * `subshell` binary. Walks `apps/node/web/dist`, base64s every file, and
 * OVERWRITES `src/generated/embedded-web.ts` with a static module
 * `dashboard/static.ts` imports (project rule: no dynamic imports, so the
 * bytes ship as a plain TS module).
 *
 * A port of the server's `apps/server/api/src/scripts/embed-web.ts` (which is
 * AGPL; this app is Apache — the deliberate-copy precedent `log-file.ts`
 * states, paths aside). Same release dance as `release:cli-server`: run BEFORE
 * `bun build --compile`, restore the stub with `git checkout` after.
 *
 * Deliberately OUTSIDE the runtime import graph: the compiled binary never
 * sees this file, tests import only the pure exports, and the CLI entry is
 * guarded by `import.meta.main`.
 */

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
/** `apps/node/agent` — the app whose `src/generated/` this script writes into. */
const AGENT_DIR = resolve(SCRIPT_DIR, "..", "..");

/** Recursively collect every file under `dir` into `out`, keyed dist-relative. */
async function walk(dir: string, base: string, out: Record<string, string>): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });
  // Sorted traversal keeps the emitted map deterministic for identical dists.
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full, base, out);
      continue;
    }
    if (!entry.isFile()) continue;
    // POSIX keys regardless of host separator — the static module looks up
    // these exact strings, and the dist layout is POSIX everywhere it builds.
    const rel = relative(base, full).split(sep).join("/");
    out[rel] = (await readFile(full)).toString("base64");
  }
}

/**
 * Reads a built frontend dist into a map of POSIX dist-relative path → base64
 * of the exact file bytes (binary assets included — base64 is byte-exact,
 * invalid UTF-8 survives).
 * @param distDir - directory to walk (`apps/node/web/dist` at release time)
 * @throws when `distDir` cannot be read or holds no `index.html` — the SPA
 * shell is mandatory, so a dist without it fails the build loudly here rather
 * than shipping a binary that shows the no-dashboard notice to every browser.
 */
export async function collectDist(distDir: string): Promise<Record<string, string>> {
  const base = resolve(distDir);
  const map: Record<string, string> = {};
  await walk(base, base, map);
  if (map["index.html"] === undefined) {
    throw new Error(`embed-web: index.html not found in ${base}; run the frontend build first`);
  }
  return map;
}

/**
 * Renders the TypeScript source of the generated module for a collected map.
 * Keys are sorted so regenerating from an identical dist is byte-identical.
 * @param map - the {@link collectDist} output
 */
export function emitModule(map: Record<string, string>): string {
  const keys = Object.keys(map).sort();
  const entries = keys.map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(map[key])},`);
  return [
    "// GENERATED by src/scripts/embed-web.ts — do not edit",
    `// ${keys.length} file(s) of the built dashboard, base64-encoded at release time.`,
    "// Served by dashboard/static.ts when no dist dir is on disk;",
    "// the tracked stub of this file says EMBEDDED = false and maps nothing.",
    "",
    "export const EMBEDDED = true;",
    "",
    "export const EMBEDDED_WEB: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

/** CLI: `apps/node/web/dist` (sibling of this app) → src/generated/embedded-web.ts. */
async function main(): Promise<void> {
  const distDir = resolve(AGENT_DIR, "..", "web", "dist");
  const map = await collectDist(distDir);
  const outPath = join(AGENT_DIR, "src", "generated", "embedded-web.ts");
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, emitModule(map));
  const files = Object.keys(map).length;
  const bytes = Object.values(map).reduce((sum, value) => sum + value.length, 0);
  process.stdout.write(`embed-web: ${files} file(s), ${bytes} base64 bytes from ${distDir} → ${outPath}\n`);
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    process.stderr.write(`embed-web: ${error instanceof Error ? error.message : String(error)}\n`);
    process.exit(1);
  });
}
