#!/usr/bin/env bun
/**
 * Keep U+2014 out of the repository's authored prose (operator ruling,
 * 2026-09-25). The docs SITE carries the same rule as a content test; this is
 * its twin for everything else a human reads in this repository: the root and
 * per-app AGENTS.md files, docs/, .claude/rules/, READMEs, and the
 * pending .changeset notes that become tomorrow's CHANGELOG entries, and
 * visitor-facing website copy in app/, components/, and lib/ source files.
 *
 * The rule, from apps/docs/AGENTS.md: no em dashes in prose, headings or
 * callouts. A comma, a colon, parentheses, or a full stop and a new sentence
 * carry the same breath honestly; the dash is the tell of a sentence that kept
 * growing. En dashes (ranges) and hyphens are untouched, and this check does
 * not "fix" them.
 *
 * What is EXEMPT and why:
 *
 *  - Fenced code blocks and inline code spans: they quote command output and
 *    literal strings (the site's content test exempts them identically).
 *  - docs/superpowers/**: dated specs and plans. They are the record of what
 *    was decided on a day, not live prose; rewriting them would edit history.
 *  - CHANGELOG.md files: build artifacts, regenerated by changesets from the
 *    .changeset notes (root AGENTS.md says to treat them as such). The notes
 *    ARE swept, so future entries come out clean on their own.
 *  - .agents/skills/**: vendored third-party skill docs, not our voice.
 *  - .claude/cache/** and anything git does not track.
 *
 *   bun scripts/prose-dashes.ts            # check (CI lint job)
 *   bun scripts/prose-dashes.ts --verbose  # also list each clean file's count
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parse } from "@babel/parser";

/** Directories whose .md files are exempt, with the reason in the comment. */
const EXCLUDED = [
  "docs/superpowers/", // dated records, not live prose
  ".agents/skills/", // vendored
  ".claude/cache/", // generated
  "apps/docs/content/", // the site's own content test owns these
];

function isExcluded(path: string): boolean {
  if (EXCLUDED.some((dir) => path.startsWith(dir) || path.includes(`/${dir}`))) return true;
  if (path.endsWith("CHANGELOG.md")) return true; // regenerated from changesets
  return false;
}

/**
 * The prose of a markdown source: fenced blocks removed (a fence only closes
 * at a matching ``` at line start), then inline code spans removed. Mirrors
 * the site's content-tree test, which strips the same two things.
 */
export function proseOf(source: string): string {
  return source.replace(/```[\s\S]*?(```|$)/g, "").replace(/`[^`\n]*`/g, "");
}

/** Website text and string values, excluding comments and explicit code examples. */
export function websiteProseOf(source: string, file: string): string {
  const ast = parse(source, { sourceType: "module", plugins: ["typescript", "jsx"], sourceFilename: file });
  const text: string[] = [];
  function visit(value: unknown): void {
    if (!value || typeof value !== "object") return;
    if (Array.isArray(value)) {
      for (const child of value) visit(child);
      return;
    }
    const node = value as Record<string, unknown>;
    if (node.type === "JSXElement") {
      const opening = node.openingElement as { name: { type: string; name?: string } };
      if (opening.name.type === "JSXIdentifier" && ["pre", "code"].includes(opening.name.name ?? "")) return;
    }
    if (node.type === "JSXText" || node.type === "StringLiteral") text.push(String(node.value));
    if (node.type === "TemplateElement") {
      const template = node.value as { cooked: string | null; raw: string };
      text.push(template.cooked ?? template.raw);
    }
    for (const child of Object.values(node)) visit(child);
  }
  visit(ast);
  return text.join("\n");
}

/** Include new files before staging, so local checks catch new website sections. */
export function proseFiles(cwd: string): string[] {
  const listed = Bun.spawnSync(
    [
      "git",
      "ls-files",
      "--cached",
      "--others",
      "--exclude-standard",
      "--",
      "*.md",
      "apps/website/app",
      "apps/website/components",
      "apps/website/lib",
    ],
    { cwd },
  );
  if (listed.exitCode !== 0) throw new Error("prose-dashes: git ls-files failed");
  return [...new Set(listed.stdout.toString().split("\n").filter(Boolean))].filter(
    (file) =>
      existsSync(join(cwd, file)) &&
      (file.endsWith(".md") || (/\.[cm]?tsx?$/.test(file) && !file.includes("/__tests__/"))),
  );
}

export interface Violation {
  file: string;
  count: number;
}

/** Authored Markdown and website copy with em dashes. Pure given the file list. */
export function violations(
  files: string[],
  read: (path: string) => string = (p) => readFileSync(p, "utf8"),
): Violation[] {
  const out: Violation[] = [];
  for (const file of files) {
    if (isExcluded(file)) continue;
    const source = read(file);
    const prose = file.endsWith(".md") ? proseOf(source) : websiteProseOf(source, file);
    const hits = prose.match(/—/g);
    if (hits !== null) out.push({ file, count: hits.length });
  }
  return out;
}

if (import.meta.main) {
  const files = proseFiles(process.cwd());
  const found = violations(files);
  const verbose = process.argv.includes("--verbose");
  for (const v of found) console.error(`${v.file}: ${v.count} em dash(es) in prose`);
  if (found.length > 0) {
    console.error(
      `\nprose-dashes: ${found.length} file(s) carry U+2014 in prose. A comma, colon,\n` +
        "parentheses, or a full stop and a new sentence carry the same breath (operator\nruling 2026-09-25; the voice rule lives in apps/docs/AGENTS.md). Fenced code,\nen dashes and hyphens are exempt.",
    );
    process.exit(1);
  }
  if (verbose) console.log(`prose-dashes: ${files.length} prose files checked, 0 violations`);
  else console.log("prose-dashes: clean");
}
