import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  // Resolves the OpenGraph image (and any root-relative URL) to absolute; a
  // crawler needs `https://subshell.sh/og.png`, not `/og.png`.
  metadataBase: new URL("https://subshell.sh"),
  title: "Subshell: manage multiple agents away from your desk",
  description:
    "Your agents keep working after you walk away. View progress, get notified, and give feedback from any device with Subshell.",
  // The same generated brand icons the SPA ships (apps/server/web/public/
  // icons, copied into ./public/icons), so the site and the installed
  // product show one mark.
  icons: {
    icon: [
      { url: "/icons/favicon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/icons/favicon.ico", type: "image/x-icon" },
    ],
    apple: "/icons/apple-touch-icon.png",
  },
  // The share card (brand/src/share-card.svg, rendered by brand:generate to
  // public/og.png at the 1200x630 large-image size). Declared here, not via
  // the opengraph-image file convention, so the ONE generated bytes file
  // serves every site that shows it and the alt text is chosen, not derived.
  openGraph: {
    type: "website",
    siteName: "Subshell",
    title: "Subshell: manage multiple agents away from your desk",
    description:
      "Your agents keep working after you walk away. View progress, get notified, and give feedback from any device.",
    images: [{ url: "/og.png", width: 1200, height: 630, alt: "Subshell: your whole agent fleet, from any device." }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Subshell: manage multiple agents away from your desk",
    description:
      "Your agents keep working after you walk away. View progress, get notified, and give feedback from any device.",
    images: ["/og.png"],
  },
};

export const viewport: Viewport = {
  // The site's own --void, so the browser chrome matches the page.
  themeColor: "#1d182a",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
