/** Declarative form contract shared by the server, CLI and bundled recovery UI. */
export type RestoreMode = "same-machine" | "migration";

export interface RestoreAddressOverrides {
  baseUrl?: string;
  host?: string;
  port?: string | number;
  trustedOrigins?: string;
}

export interface BackupRestoreChoices {
  mode: RestoreMode;
  configOverrides?: RestoreAddressOverrides;
}

export const BACKUP_RESTORE_DEFAULTS = {
  mode: "same-machine" as RestoreMode,
  recoverAdmin: false,
  start: true,
  encrypt: false,
} as const;

export const BACKUP_RESTORE_MODES = [
  { value: "same-machine", label: "Same-machine recovery" },
  { value: "migration", label: "Move to a new machine" },
] as const;

/** Shared archive-password policy; never trim or normalize password values. */
export function backupEncryptionPasswordProblem(password: string): string | null {
  if (password.length > 4096 || /[\r\n\0]/.test(password))
    return "Use a password of at most 4096 characters on one line.";
  if (Array.from(password).length < 8) return "Use at least 8 characters for the archive password.";
  return null;
}

export const BACKUP_PASSWORD_GUIDANCE =
  "Use a unique password generated by a password manager or a long random passphrase. Store it separately; a forgotten archive password cannot be recovered.";
