/** Declarative form contract shared by the server, CLI and bundled recovery UI. */
export type RestoreMode = "same-machine" | "migration";

export interface RestoreAddressOverrides {
  baseUrl?: string;
  host?: string;
  port?: string | number;
  trustedOrigins?: string;
}

export interface BackupRestoreChoices {
  mode: RestoreMode;
  configOverrides?: RestoreAddressOverrides;
}

export const BACKUP_RESTORE_DEFAULTS = {
  mode: "same-machine" as RestoreMode,
  recoverAdmin: false,
  start: true,
  encrypt: false,
} as const;

export const BACKUP_RESTORE_MODES = [
  {
    value: "same-machine",
    label: "Same-machine recovery",
    description:
      "Restore this server on its original machine, keeping the backup’s network settings and publication configuration.",
  },
  {
    value: "migration",
    label: "This machine is different from the original",
    description:
      "Use when restoring here from a backup created on a different machine. Network plugins are disabled and published addresses are cleared so you can review them before reconnecting. The server’s identity and credentials are kept.",
  },
] as const;

/** Shared archive-password policy; never trim or normalize password values. */
export function backupEncryptionPasswordProblem(password: string): string | null {
  if (password.length > 4096 || /[\r\n\0]/.test(password))
    return "Use a password of at most 4096 characters on one line.";
  if (Array.from(password).length < 8) return "Use at least 8 characters for the archive password.";
  return null;
}

export const BACKUP_PASSWORD_GUIDANCE =
  "Use a unique password generated by a password manager or a long random passphrase. Store it separately; a forgotten archive password cannot be recovered.";
