export type { BackupRestoreChoices, RestoreAddressOverrides, RestoreMode } from "./backup.js";
export {
  BACKUP_PASSWORD_GUIDANCE,
  BACKUP_RESTORE_DEFAULTS,
  BACKUP_RESTORE_MODES,
  backupEncryptionPasswordProblem,
} from "./backup.js";
export {
  type DeviceReport,
  type DeviceRole,
  type DeviceRow,
  describeDevices,
  roleLabel,
  type ViewersState,
} from "./device-roles.js";
export {
  dirAllowed,
  dirNavigable,
  MAX_ALLOWED_DIRS,
  normalizeAllowedDir,
  normalizeAllowedDirs,
} from "./dir-allowlist.js";
export {
  BRACKETED_PASTE_END,
  BRACKETED_PASTE_START,
  type ClientFrame,
  DEVICE_LABEL_MAX,
  NODE_NAME_MAX,
  NODE_NAME_MAX_UNITS,
  normalizeDeviceLabel,
  normalizeLabel,
  normalizeNodeName,
  parseClientFrame,
  type ServerFrame,
  type ViewerPresence,
} from "./frames.js";
export type { JsonValue } from "./json.js";
export {
  COMPANY_URL,
  COPYRIGHT_HOLDER,
  COPYRIGHT_LINE,
  COPYRIGHT_YEAR,
  LICENSE_EXCEPTION_SUMMARY,
  LICENSE_SUMMARY,
  LICENSE_URL,
  licenseNotice,
  PRODUCT_NAME,
  PRODUCT_URL,
} from "./legal.js";
export {
  type LingerProbeResult,
  lingerFromProbe,
  lingerProbeArgv,
  lingerVerdict,
} from "./linger.js";
// NOTE: release-artifacts.ts, release-signature.ts and service-test-safety.ts
// (node: builtins) are intentionally NOT re-exported here — this barrel is
// imported by apps/client/mobile through Metro, which cannot resolve
// `node:*`. Consumers import "@internal/subshell-protocol/release-artifacts",
// ".../release-signature" and ".../service-test-safety". Adding any of them to
// this barrel breaks the mobile build and nothing else, so it fails in CI
// rather than locally; that is how service-test-safety got here in the first
// place (2026-09-15).
export {
  type LiveClientFrame,
  type LiveServerFrame,
  parseLiveClientFrame,
} from "./live-frames.js";
export {
  type DetectSpecWire,
  HARNESS_BINARY_PLACEHOLDER,
  type HarnessSessionWire,
  isNodeServiceVerb,
  isNodeSubshellId,
  type LaunchResolveWire,
  MAX_ARCHIVE_BYTES,
  MAX_ARCHIVE_ENTRIES,
  MAX_ARCHIVE_FILE_BYTES,
  MAX_MANIFEST_PAGE_BYTES,
  MAX_MANIFEST_PAGE_ENTRIES,
  MAX_TRANSFER_LIST_FILES,
  MAX_TRANSFER_WINDOW_BYTES,
  NODE_CLOSE_HANDSHAKE_REQUIRED,
  NODE_CLOSE_REPAIR_REQUIRED,
  NODE_CLOSE_SUPERSEDED,
  NODE_CLOSE_UPDATE_REQUIRED,
  NODE_MAX_FRAME_BYTES,
  NODE_PROTOCOL_VERSION,
  NODE_RESULT_DIGEST_MISMATCH,
  NODE_RESULT_DOWNLOAD_FAILED,
  NODE_RESULT_KILLS_PANES,
  NODE_RESULT_MAINTENANCE,
  NODE_RESULT_MANIFEST_UNVERIFIED,
  NODE_RESULT_NO_SERVICE,
  NODE_RESULT_NOT_COMPILED,
  NODE_RESULT_NOT_SUPERVISED,
  NODE_RESULT_VERSION_MISMATCH,
  NODE_SERVICE_DESTRUCTIVE,
  NODE_SERVICE_VERBS,
  NODE_SIGNED_UPDATES_PROTOCOL_VERSION,
  type NodeCommandBody,
  type NodeEvent,
  type NodeMaintenanceWire,
  type NodeRuntimeReport,
  type NodeServiceVerb,
  type PluginReportWire,
  type PresetDefinitionWire,
  parseNodeCommandBody,
  parseNodeEvent,
  parseNodeMaintenance,
  parseNodeRuntimeReport,
  partPathOf,
} from "./node-frames.js";
export {
  type DetectResultWire,
  FS_LS_MAX_ENTRIES,
  type NodeAgentLogSlice,
  type NodeArchiveCreateResult,
  type NodeArchiveExtractResult,
  type NodeFileReadResult,
  type NodeFsLsResult,
  type NodeLogReadResult,
  type NodeManifestEntryWire,
  type NodePaneCursorResult,
  type NodePaneSizeResult,
  type NodePathExistsResult,
  type NodeProbeEntry,
  type NodePromptDeliverResult,
  type NodeStatDirResult,
  type NodeTreeManifestPage,
  type NodeWriteFileResult,
  parseNodeAgentLogSlice,
  parseNodeArchiveCreateResult,
  parseNodeArchiveExtractResult,
  parseNodeCaptureResult,
  parseNodeDetectResults,
  parseNodeFileReadResult,
  parseNodeFsLsResult,
  parseNodeLogReadResult,
  parseNodePaneCursorResult,
  parseNodePaneSizeResult,
  parseNodePathExistsResult,
  parseNodeProbeEntries,
  parseNodePromptDeliver,
  parseNodeSshAliasList,
  parseNodeSshControlResult,
  parseNodeSshResolveOutcome,
  parseNodeSshRunFacts,
  parseNodeSshRunReadResult,
  parseNodeSshSessionOpenResult,
  parseNodeSshTestOutcome,
  parseNodeStatDirResult,
  parseNodeTreeManifestPage,
  parseNodeWriteFileResult,
} from "./node-results.js";
export {
  type CommandClaims,
  type ControlKeyPair,
  generateControlKeys,
  JtiLru,
  NODE_CMD_ISSUER,
  NODE_CMD_TTL_SEC,
  SeqTracker,
  type SignCommandInput,
  signCommand,
  /** @internal test-only export (see node-signing.ts) */
  signRawClaims,
  type VerifyContext,
  type VerifyOutcome,
  verifyCommand,
} from "./node-signing.js";
export {
  CLI_SUFFIX,
  DEFAULT_DATABASE_PATH,
  DESKTOP_CLIENT_BUNDLE_ID,
  DESKTOP_CLIENT_PRODUCT,
  DESKTOP_SERVER_BUNDLE_ID,
  DESKTOP_SERVER_PRODUCT,
  DESKTOP_SUFFIX,
  DESKTOP_TARGETS,
  type DesktopTarget,
  defaultSubshellServerDataDir,
  desktopArtifactFileName,
  desktopSidecarFileName,
  NODE_SIDECAR_NAME,
  NODE_TARGETS,
  type NodeArtifactsEnv,
  type NodeTarget,
  nodeArtifactFileName,
  resolveNodeArtifactsDir,
  rustTargetTriple,
  SERVER_SIDECAR_NAME,
  SERVER_TARGETS,
  type ServerTarget,
  serverArtifactFileName,
} from "./paths.js";
export {
  isPresetCrossCommReady,
  joinPresetPrompt,
  type PresetPromptBlock,
  parsePresetPromptBlocks,
  presetLaunchRequirementsMet,
} from "./preset-prompt.js";
export {
  DEFAULT_RELEASE_API,
  hostReleaseTarget,
  newestRelease,
  parseReleaseManifest,
  parseReleaseTag,
  parseSidecarDigest,
  RELEASE_COMPONENTS,
  RELEASE_MANIFEST_NAME,
  RELEASE_MANIFEST_SIG_NAME,
  RELEASE_PUBKEY,
  RELEASE_TAG_PREFIX,
  type ReleaseCandidate,
  type ReleaseComponent,
  type ReleaseManifest,
  releaseAssetNames,
  SUBSHELL_REPO_SLUG,
} from "./releases.js";
export {
  DEFAULT_GRID,
  DEFAULT_SIZING,
  decideSharedGrid,
  type Grid,
  type GridDecision,
  type GridReason,
  MIN_SHARED_COLS,
  MIN_SHARED_ROWS,
  resolveSharedGrid,
  type SizingMode,
  type SizingPolicy,
  type ViewerCapacity,
} from "./shared-geometry.js";
export {
  parseSshConnectionSnapshot,
  SSH_FORBIDDEN_SNAPSHOT_FIELDS,
  type SshConnectionSnapshotWire,
  type SshForbiddenSnapshotField,
  type SshHopWire,
} from "./ssh-config.js";
export {
  isSshErrorCode,
  SSH_ERROR_CODES,
  SSH_ERROR_DESCRIPTIONS,
  type SshErrorCode,
} from "./ssh-errors.js";
export {
  parseSshNodeCommandBody,
  SSH_COMMAND_TYPES,
  type SshDiscoverAliasesCommand,
  type SshInputControlCommand,
  type SshNodeCommandBody,
  type SshResolveConfigCommand,
  type SshRunCancelCommand,
  type SshRunReadCommand,
  type SshRunStartCommand,
  type SshRunStatusCommand,
  type SshTerminalLaunchCommand,
  type SshTestConnectionCommand,
} from "./ssh-frames.js";
export {
  SSH_ACTIVE_RUNS_PER_NODE,
  SSH_ACTIVE_RUNS_PER_OWNER_PER_NODE,
  SSH_AGGREGATE_OUTPUT_STORAGE_BYTES,
  SSH_CANCEL_GRACE_MS,
  SSH_COMMAND_MAX_CHARS,
  SSH_COMPLETED_RUN_RETENTION_DAYS,
  SSH_COMPLETED_RUN_RETENTION_MS,
  SSH_MAX_CERT_REFS,
  SSH_MAX_DISCOVERED_ALIASES,
  SSH_MAX_IDENTITY_REFS,
  SSH_MAX_KNOWN_HOSTS_FILES,
  SSH_MAX_PROXY_HOPS,
  SSH_NAME_MAX_CHARS,
  SSH_OUTPUT_WINDOW_MAX_BYTES,
  SSH_PATH_MAX_CHARS,
  SSH_PROBE_DEADLINE_MS,
  SSH_READ_LONG_POLL_MAX_MS,
  SSH_RUN_DEADLINE_DEFAULT_MS,
  SSH_RUN_DEADLINE_MAX_MS,
  SSH_RUN_OUTPUT_RETENTION_BYTES,
  SSH_TERMINALS_PER_OWNER_PER_NODE,
} from "./ssh-limits.js";
export type {
  NodeSshAliasListResult,
  NodeSshControlResult,
  NodeSshResolveOutcomeWire,
  NodeSshRunReadResult,
  NodeSshTestOutcomeWire,
} from "./ssh-results.js";
export {
  NODE_RESULT_SSH_GENERATION_STALE,
  readSshRunFacts,
  SSH_CONTROL_MODES,
  SSH_RUN_LIFECYCLES,
  type SshControlMode,
  type SshRunFactsWire,
  type SshRunLifecycle,
} from "./ssh-run-facts.js";
export {
  encodeSshSessionFrame,
  SSH_SESSION_FRAME_MAX_BYTES,
  type SshSessionCodecFailure,
  SshSessionFrameDecoder,
} from "./ssh-session-codec.js";
export {
  isSshSessionRef,
  parseSshRuntimeCommandFrame,
  parseSshRuntimeEventFrame,
  parseSshRuntimeHello,
  parseSshRuntimeReportRows,
  parseSshSessionNodeCommandBody,
  parseSshSessionOpenResult,
  parseSshSessionTarget,
  sshRuntimeProtocolSupported,
} from "./ssh-session-frame-parsers.js";
export {
  SSH_RUNTIME_PROTOCOL,
  SSH_SESSION_COMMAND_TYPES,
  SSH_SESSION_INBOUND_QUEUE_FRAMES,
  SSH_SESSION_OPEN_DEADLINE_MS,
  SSH_SESSION_RUNTIME_MISSING,
  SSH_SESSION_UNKNOWN,
  SSH_SESSIONS_PER_NODE,
  type SshRuntimeCommandFrame,
  type SshRuntimeEventFrame,
  type SshRuntimeHelloWire,
  type SshRuntimeLaunchBody,
  type SshRuntimeReportRow,
  type SshSessionCloseCommand,
  type SshSessionNodeCommandBody,
  type SshSessionOpenCommand,
  type SshSessionOpenResultWire,
  type SshSessionSendCommand,
  type SshSessionTargetWire,
} from "./ssh-session-frames.js";
export { MAX_UPLOAD_BYTES } from "./uploads.js";
export { MIN_NODE_VERSION, nodeVersionSupported, semverLt } from "./versions.js";
