export {
  type DeviceReport,
  type DeviceRole,
  type DeviceRow,
  describeDevices,
  roleLabel,
  type ViewersState,
} from "./device-roles.js";
export {
  dirAllowed,
  dirNavigable,
  MAX_ALLOWED_DIRS,
  normalizeAllowedDir,
  normalizeAllowedDirs,
} from "./dir-allowlist.js";
export {
  BRACKETED_PASTE_END,
  BRACKETED_PASTE_START,
  type ClientFrame,
  DEVICE_LABEL_MAX,
  normalizeDeviceLabel,
  normalizeLabel,
  parseClientFrame,
  type ServerFrame,
  type ViewerPresence,
} from "./frames.js";
export type { JsonValue } from "./json.js";
export {
  COMPANY_URL,
  COPYRIGHT_HOLDER,
  COPYRIGHT_LINE,
  COPYRIGHT_YEAR,
  LICENSE_EXCEPTION_SUMMARY,
  LICENSE_SUMMARY,
  LICENSE_URL,
  licenseNotice,
  PRODUCT_NAME,
  PRODUCT_URL,
} from "./legal.js";
// NOTE: release-artifacts.ts (node: builtins) is intentionally NOT re-exported
// here — this barrel is imported by apps/client/mobile through Metro, which cannot
// resolve `node:*`. Consumers import "@internal/subshell-protocol/release-artifacts".
export {
  type LingerProbeResult,
  lingerFromProbe,
  lingerProbeArgv,
  lingerVerdict,
} from "./linger.js";
export {
  type DetectSpecWire,
  HARNESS_BINARY_PLACEHOLDER,
  type HarnessSessionWire,
  isNodeServiceVerb,
  isNodeSubshellId,
  type LaunchResolveWire,
  NODE_CLOSE_SUPERSEDED,
  NODE_CLOSE_UPDATE_REQUIRED,
  NODE_MAX_FRAME_BYTES,
  NODE_PROTOCOL_VERSION,
  NODE_RESULT_KILLS_PANES,
  NODE_RESULT_MAINTENANCE,
  NODE_RESULT_NO_SERVICE,
  NODE_RESULT_NOT_SUPERVISED,
  NODE_SERVICE_DESTRUCTIVE,
  NODE_SERVICE_VERBS,
  type NodeCommandBody,
  type NodeEvent,
  type NodeMaintenanceWire,
  type NodeRuntimeReport,
  type NodeServiceVerb,
  type PluginReportWire,
  type PresetDefinitionWire,
  parseNodeCommandBody,
  parseNodeEvent,
  parseNodeMaintenance,
  parseNodeRuntimeReport,
} from "./node-frames.js";
export {
  DEFAULT_NODE_RELEASE_API,
  NODE_RELEASE_TAG_PREFIX,
  type NodeReleaseCandidate,
  newestNodeRelease,
  nodeReleaseAssetNames,
  parseNodeReleaseTag,
  parseSidecarDigest,
  SUBSHELL_REPO_SLUG,
} from "./node-release.js";
export {
  type DetectResultWire,
  FS_LS_MAX_ENTRIES,
  type NodeAgentLogSlice,
  type NodeFsLsResult,
  type NodeLogReadResult,
  type NodePaneSizeResult,
  type NodePathExistsResult,
  type NodeProbeEntry,
  type NodePromptDeliverResult,
  type NodeStatDirResult,
  type NodeWriteFileResult,
  parseNodeAgentLogSlice,
  parseNodeCaptureResult,
  parseNodeDetectResults,
  parseNodeFsLsResult,
  parseNodeLogReadResult,
  parseNodePaneSizeResult,
  parseNodePathExistsResult,
  parseNodeProbeEntries,
  parseNodePromptDeliver,
  parseNodeStatDirResult,
  parseNodeWriteFileResult,
} from "./node-results.js";
export {
  type CommandClaims,
  type ControlKeyPair,
  generateControlKeys,
  JtiLru,
  NODE_CMD_ISSUER,
  NODE_CMD_TTL_SEC,
  SeqTracker,
  type SignCommandInput,
  signCommand,
  /** @internal test-only export (see node-signing.ts) */
  signRawClaims,
  type VerifyContext,
  type VerifyOutcome,
  verifyCommand,
} from "./node-signing.js";
export {
  AGENT_SIDECAR_NAME,
  CLI_SUFFIX,
  DEFAULT_DATABASE_PATH,
  DESKTOP_CLIENT_BUNDLE_ID,
  DESKTOP_CLIENT_PRODUCT,
  DESKTOP_SERVER_BUNDLE_ID,
  DESKTOP_SERVER_PRODUCT,
  DESKTOP_SUFFIX,
  DESKTOP_TARGETS,
  type DesktopTarget,
  defaultSubshellServerDataDir,
  desktopArtifactFileName,
  desktopSidecarFileName,
  NODE_TARGETS,
  type NodeArtifactsEnv,
  type NodeTarget,
  nodeArtifactFileName,
  resolveNodeArtifactsDir,
  rustTargetTriple,
  SERVER_SIDECAR_NAME,
  SERVER_TARGETS,
  type ServerTarget,
  serverArtifactFileName,
} from "./paths.js";
export {
  assertManagerCommandUnderTest,
  assertServiceWriteUnderTest,
} from "./service-test-safety.js";
export {
  DEFAULT_GRID,
  DEFAULT_SIZING,
  decideSharedGrid,
  type Grid,
  type GridDecision,
  type GridReason,
  MIN_SHARED_COLS,
  MIN_SHARED_ROWS,
  resolveSharedGrid,
  type SizingMode,
  type SizingPolicy,
  type ViewerCapacity,
} from "./shared-geometry.js";
export { MAX_UPLOAD_BYTES } from "./uploads.js";
export { agentVersionSupported, MIN_AGENT_VERSION, semverLt } from "./versions.js";
