/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as ProfilesIdRouteImport } from './routes/profiles_.$id'
import { Route as SessionsIdRouteImport } from './routes/sessions_.$id'
import { Route as WorkspacesIdRouteImport } from './routes/workspaces_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles_/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions_/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIdRoute = WorkspacesIdRouteImport.update({
  id: '/workspaces_/$id',
  path: '/workspaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRoute
  '/profiles_/$id': typeof ProfilesIdRoute
  '/sessions_/$id': typeof SessionsIdRoute
  '/workspaces_/$id': typeof WorkspacesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/new'
    | '/profiles'
    | '/settings'
    | '/setup'
    | '/users'
    | '/workspaces'
    | '/profiles/$id'
    | '/sessions/$id'
    | '/workspaces/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/new'
    | '/profiles'
    | '/settings'
    | '/setup'
    | '/users'
    | '/workspaces'
    | '/profiles/$id'
    | '/sessions/$id'
    | '/workspaces/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/new'
    | '/profiles'
    | '/settings'
    | '/setup'
    | '/users'
    | '/workspaces'
    | '/profiles_/$id'
    | '/sessions_/$id'
    | '/workspaces_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ProfilesRoute: typeof ProfilesRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
  WorkspacesRoute: typeof WorkspacesRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  SessionsIdRoute: typeof SessionsIdRoute
  WorkspacesIdRoute: typeof WorkspacesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles_/$id': {
      id: '/profiles_/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/$id': {
      id: '/sessions_/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$id': {
      id: '/workspaces_/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof WorkspacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
  WorkspacesRoute: WorkspacesRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  SessionsIdRoute: SessionsIdRoute,
  WorkspacesIdRoute: WorkspacesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
