/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as NodesIdRouteImport } from './routes/nodes_.$id'
import { Route as ProfilesIdRouteImport } from './routes/profiles_.$id'
import { Route as SubshellsIdRouteImport } from './routes/subshells_.$id'
import { Route as WorkspacesIdRouteImport } from './routes/workspaces_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIdRoute = NodesIdRouteImport.update({
  id: '/nodes_/$id',
  path: '/nodes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles_/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubshellsIdRoute = SubshellsIdRouteImport.update({
  id: '/subshells_/$id',
  path: '/subshells/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIdRoute = WorkspacesIdRouteImport.update({
  id: '/workspaces_/$id',
  path: '/workspaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRoute
  '/nodes/$id': typeof NodesIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/subshells/$id': typeof SubshellsIdRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRoute
  '/nodes/$id': typeof NodesIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/subshells/$id': typeof SubshellsIdRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/nodes': typeof NodesRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/workspaces': typeof WorkspacesRoute
  '/nodes_/$id': typeof NodesIdRoute
  '/profiles_/$id': typeof ProfilesIdRoute
  '/subshells_/$id': typeof SubshellsIdRoute
  '/workspaces_/$id': typeof WorkspacesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/new'
    | '/nodes'
    | '/profiles'
    | '/settings'
    | '/setup'
    | '/users'
    | '/workspaces'
    | '/nodes/$id'
    | '/profiles/$id'
    | '/subshells/$id'
    | '/workspaces/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/new'
    | '/nodes'
    | '/profiles'
    | '/settings'
    | '/setup'
    | '/users'
    | '/workspaces'
    | '/nodes/$id'
    | '/profiles/$id'
    | '/subshells/$id'
    | '/workspaces/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/new'
    | '/nodes'
    | '/profiles'
    | '/settings'
    | '/setup'
    | '/users'
    | '/workspaces'
    | '/nodes_/$id'
    | '/profiles_/$id'
    | '/subshells_/$id'
    | '/workspaces_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  NodesRoute: typeof NodesRoute
  ProfilesRoute: typeof ProfilesRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
  WorkspacesRoute: typeof WorkspacesRoute
  NodesIdRoute: typeof NodesIdRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  SubshellsIdRoute: typeof SubshellsIdRoute
  WorkspacesIdRoute: typeof WorkspacesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes_/$id': {
      id: '/nodes_/$id'
      path: '/nodes/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof NodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles_/$id': {
      id: '/profiles_/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subshells_/$id': {
      id: '/subshells_/$id'
      path: '/subshells/$id'
      fullPath: '/subshells/$id'
      preLoaderRoute: typeof SubshellsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$id': {
      id: '/workspaces_/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof WorkspacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  NodesRoute: NodesRoute,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
  WorkspacesRoute: WorkspacesRoute,
  NodesIdRoute: NodesIdRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  SubshellsIdRoute: SubshellsIdRoute,
  WorkspacesIdRoute: WorkspacesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
