export {
  type DetectSpec,
  type InstallSpec,
  type ManifestError,
  PLUGIN_API_VERSION,
  parseManifest,
  type SubshellManifest,
} from "./manifest.js";
export {
  type BuildCommandInput,
  capabilityMismatches,
  type DetectionReason,
  type DetectionResult,
  type HarnessResume,
  MCP_SERVER_NAME,
  type McpLaunchSpec,
  type McpRegistration,
  type McpSetupInfo,
  type McpSetupStep,
  PLUGIN_CAPABILITIES,
  PLUGIN_TYPES,
  type PluginCapability,
  type PluginFactory,
  type PluginHost,
  type PluginType,
  type ProfileDefinition,
  type ProfileValidationIssue,
  type ProfileValidationResult,
  type SettingsField,
  type SubshellPlugin,
  shellQuote,
} from "./types.js";
export { validateGenericProfile } from "./validate.js";
